// components/Footer.vue
<script setup>
const year = new Date().getFullYear();

const socialLinks = [
    {
        name: 'Facebook',
        url: 'https://facebook.com/tylergrinsteaddesign',
        icon: 'M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z'
    },
    {
        name: 'Instagram',
        url: 'https://instagram.com/txgrinstead',
        icon: 'M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z'
    }
];
</script>

<template>
    <footer class="bg-slate-800 text-white py-10">
        <div class="container mx-auto px-4">
            <div class="max-w-5xl mx-auto flex flex-col md:flex-row items-center justify-between">
                <!-- Logo section -->
                <div class="mb-6 md:mb-0">
                    <img src="/assets/tgdio.webp" alt="TG Design & Development, LLC Logo" class="h-12 invert"
                        loading="lazy">
                </div>

                <!-- Copyright section -->
                <div class="mb-6 md:mb-0 text-center">
                    <p class="text-gray-300">
                        &copy; {{ year }} TG Design & Development, LLC. All rights reserved.
                    </p>
                    <p class="text-gray-400 text-sm mt-1">
                        Crafting exceptional digital experiences for your business.
                    </p>
                </div>

                <!-- Social links section -->
                <div class="flex items-center space-x-4">
                    <a v-for="social in socialLinks" :key="social.name" :href="social.url" target="_blank"
                        rel="noopener noreferrer" class="text-gray-400 hover:text-white transition-colors duration-300"
                        :aria-label="social.name">
                        <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                            <path :d="social.icon" />
                        </svg>
                    </a>
                </div>
            </div>

            <!-- Navigation links -->
            <div class="max-w-5xl mx-auto mt-8 pt-8 border-t border-gray-700">
                <div class="flex flex-wrap justify-center gap-x-8 gap-y-4 text-sm text-gray-400">
                    <NuxtLink to="/about/" class="hover:text-white transition-colors duration-300">About</NuxtLink>
                    <NuxtLink to="/services/" class="hover:text-white transition-colors duration-300">Services
                    </NuxtLink>
                </div>
            </div>
        </div>
    </footer>
</template>

// src/components/Footer.jsx
import { Facebook, Instagram, Mail } from 'lucide-react';
import React from 'react';

const Footer = ({ theme }) => {
  return (
    <footer className="bg-slate-950 border-slate-900 border-t py-12 px-6 transition-colors duration-500">
      <div className="max-w-7xl mx-auto mb-12 grid md:grid-cols-2 gap-12">
        <div>
          <div className="flex items-center gap-2 mb-6">
            <div className="w-8 h-8 bg-cyan-600 rounded flex items-center justify-center text-xs font-bold text-slate-900">TG</div>
            <span className="font-bold text-xl text-slate-300">TG Design & Development</span>
          </div>
          <p className={`${theme.textMuted} max-w-sm`}>
            Forging digital identities that stand the test of time.
          </p>
        </div>

        <div>
          <h2 className={`font-bold uppercase tracking-widest text-sm mb-6 ${theme.accentText}`}>Our Beliefs</h2>
          <div className="space-y-4">
            <div>
              <h4 className={`font-bold ${theme.text} mb-1`}>The Internet is for everyone.</h4>
              <p className={`${theme.textMuted} text-sm`}>Small businesses deserve the same digital polish and presence as the Fortune 500.</p>
            </div>
            <div>
              <h4 className={`font-bold ${theme.text} mb-1`}>Authenticity wins.</h4>
              <p className={`${theme.textMuted} text-sm`}>People buy from people. Your website shouldn't look like a template; it should look like you.</p>
            </div>
            <div>
              <h4 className={`font-bold ${theme.text} mb-1`}>DIY isn't the answer.</h4>
              <p className={`${theme.textMuted} text-sm`}>You have a business to run. Stop wrestling with "drag-and-drop" tools that don't deliver. Let us handle the tech so you can handle the rest.</p>
            </div>
            <div>
              <h4 className={`font-bold ${theme.text} mb-1`}>We’re in your corner.</h4>
              <p className={`${theme.textMuted} text-sm`}>We exist to help the underdog fight, survive, and thrive in a world of big fish.</p>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center gap-8 pt-8 border-t border-slate-900">
        <div className="text-slate-400 text-sm">
          &copy; {new Date().getFullYear()} TG Design & Development, LLC. All rights reserved.
        </div>

        <div className="flex gap-6">
          <a href="https://www.facebook.com/tylergrinsteaddesign" target="_blank" rel="noopener noreferrer" aria-label="Facebook" className="text-slate-400 hover:text-cyan-600 transition-colors"><Facebook size={20} /></a>
          <a href="https://www.instagram.com/txgrinstead/" target="_blank" rel="noopener noreferrer" aria-label="Instagram" className="text-slate-400 hover:text-cyan-600 transition-colors"><Instagram size={20} /></a>
          <a href="mailto:tyler@tgdesign.io" aria-label="Email" className="text-slate-400 hover:text-cyan-600 transition-colors"><Mail size={20} /></a>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
